mysite/apps/boards/urls.py
from django.urls import path, include
from . import views

app_name = 'boards'
urlpatterns = [
    path('<int:board_id>/', views.detail, name='detail'),
    path('<int:board_id>/columns/', include('columns.urls')),
    path('<int:board_id>/tasks/', include('tasks.urls')),
    path('delete_board/<int:board_id>/', views.delete_board, name='delete_board'),
    path('create_board', views.create_board, name="create_board"),
    path('edit_board/<int:board_id>/', views.edit_board),
    path('invite_user/<int:board_id>/', views.invite_user),
]

mysite/apps/columns/urls.py
from django.contrib import admin
from django.urls import path
from columns import views

urlpatterns = [
    path('<int:column_id>/<int:board_id>', views.detail, name='detail'),
    path('create_column/<int:board_id>/', views.create_column, name="create_column"),
    path('delete_column/<int:column_id>/<int:board_id>', views.delete_column),
    path('edit_column/<int:column_id>/<int:board_id>', views.edit_column),
]

mysite/apps/tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'
urlpatterns = [
    path('', views.create_task),
    path('create_task/<int:column_id>/<int:board_id>', views.create_task,),
    path('delete_task/<int:task_id>/<int:column_id>/<int:board_id>', views.delete_task),
    path('edit_task/<int:task_id>/<int:column_id>/<int:board_id>', views.edit_task),
    path('complete_task/<int:task_id>/<int:column_id>/<int:board_id>', views.complete_task),
    # path('leave_comment/<int:task_id>/<int:board_id>', views.leave_comment),
    # path('leave', views.leave),
]

mysite/urls.py
import django
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),  # grappelli URLS
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('columns/', include('columns.urls')),
    path('tasks/', include('tasks.urls')),
    path('register/', include('register.urls')),

    path('create_board/', include('boards.urls')),
    path('create_task/', include('tasks.urls')),
    path('create_column/<int:board_id>/', include('columns.urls')),

    path('', include('account_pages.urls')),
    path('', include('django.contrib.auth.urls')),
]

mysite/apps/account_pages/models.py
from django.db import models

# Create your models here.

mysite/apps/boards/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User


class Board(models.Model):
    users = models.ManyToManyField(User, related_name='boards')
    board_title = models.CharField('Name of title', max_length=200)
    pub_date = models.DateTimeField("Date of publication")

    def __str__(self):
        return self.board_title

    def recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=7))

    class Meta:
        verbose_name = 'Доска'
        verbose_name_plural = 'Доски'

mysite/apps/columns/models.py
from django.db import models

from boards.models import Board


class Column(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name="column", null=True)
    column_title = models.CharField('Name of title', max_length=200)

    def __str__(self):
        return self.column_title

    class Meta:
        verbose_name = 'Колонка'
        verbose_name_plural = 'Колонки'

mysite/apps/tasks/models.py
from django.conf import settings
from django.db import models
from columns.models import Column


class Task(models.Model):
    column = models.ForeignKey(Column, on_delete=models.CASCADE, related_name="task", null=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    how_do_this = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="how_do")
    title = models.CharField(max_length=200)
    description = models.TextField(default="")
    pub_date = models.DateTimeField("Date of publication")
    lead_time = models.DateTimeField("Date of assignment", null=True)  # можно не заполнять
    is_completed = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'


class Comment(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='comment', null=True)  # cascade удаленные комментарии к таску
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comment_text = models.CharField('Text of comment', max_length=200)

    def __str__(self):
        return self.author

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

mysite/apps/account_pages/forms.py
from django import forms
from boards.models import Board


class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ("board_title",)

mysite/apps/boards/forms.py
from django import forms
from .models import Board


class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ("board_title",)


class UserInvitationForm(forms.Form):
    username = forms.CharField(label='Name of the user you want to add:')

mysite/apps/columns/forms.py
from django import forms
from columns.models import Column
from tasks.models import Task


class ColumnForm(forms.ModelForm):
    class Meta:
        model = Column
        fields = ("column_title",)

mysite/apps/register/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

mysite/apps/tasks/forms.py
from django import forms
from tasks.models import Comment
from tasks.models import Task


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("author", "comment_text",)


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ("title", "description", "lead_time",)

mysite/apps/account_pages/views.py
from boards.models import Board
from columns.models import Column
from django.shortcuts import render


def main(request):
    board_list = Board.objects.order_by('pub_date')
    column_list = Column.objects.all()
    return render(request, 'account_pages/home.html', {'board_list': board_list, 'column_list': column_list})

mysite/apps/boards/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.utils import timezone
from boards.models import Board
from columns.models import Column
from tasks.models import Task
from .forms import BoardForm, UserInvitationForm


@login_required(login_url='/login')
def detail(request, board_id):
    board = Board.objects.get(id=board_id)
    if request.user in board.users.all():
        columns_list = Column.objects.filter(board=board_id)
        task_list = Task.objects.all()
        return render(request, 'boards/detail.html',
                      {'board': board, 'columns_list': columns_list, 'task_list': task_list})
    else:
        return render(request, "account_pages/warning.html")


@login_required(login_url='/login')
def create_board(request):
    if request.method == "POST":
        form = BoardForm(request.POST)
        if form.is_valid():
            board = form.save(commit=False)
            board.pub_date = timezone.now()
            board.save()
            board.users.add(request.user)
        return redirect("/")
    else:
        form = BoardForm()
    return render(request, "boards/create_board.html", {"form": form})


@login_required(login_url='/login')
def delete_board(request, board_id):
    board = Board.objects.get(id=board_id)
    if request.user in board.users.all():
        board.delete()
        return redirect("/")
    else:
        return render(request, "account_pages/warning.html")


@login_required(login_url='/login')
def edit_board(request, board_id):
    if request.method == "POST":
        board_prev = Board.objects.get(id=board_id)
        if request.user in board_prev.users.all():
            form = BoardForm(request.POST, instance=board_prev)
            if form.is_valid():
                board = form.save(commit=False)
                board.pub_date = timezone.now()
                board.save()
            return redirect('/boards/{}'.format(board_id))
        else:
            return render(request, "account_pages/warning.html")
    else:
        form = BoardForm()
    return render(request, "boards/create_board.html", {"form": form})


@login_required(login_url='/login')
def invite_user(request, board_id):
    if request.method == "POST":
        form = UserInvitationForm(request.POST)
        if form.is_valid():
            board = Board.objects.get(id=board_id)
            username = form.cleaned_data['username']
            try:
                user = User.objects.get(username=username)
                board.users.add(user.id)
            except ObjectDoesNotExist:
                return render(request, "account_pages/no_such_user.html")
        return redirect('/boards/{}'.format(board_id))
    else:
        form = UserInvitationForm()
    return render(request, "boards/invite_user.html", {"form": form})

mysite/apps/columns/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import ColumnForm
from .models import Column
from boards.models import Board
from tasks.models import Task


@login_required(login_url='/login')
def detail(request, column_id, board_id):
    a = Column.objects.get(id=column_id)
    board = Board.objects.get(id=board_id)
    if a in board.column.all():
        return render(request, 'columns/detail.html', {'column': a})
    else:
        return render(request, "account_pages/warning.html")


@login_required(login_url='/login')
def create_column(request, board_id):
    if request.method == "POST":
        board = Board.objects.get(id=board_id)
        form = ColumnForm(request.POST)
        if form.is_valid():
            column = form.save(commit=False)
            column.board = board
            column.save()
            board.column.add(column)
            return redirect('/boards/{}'.format(board_id))
    else:
        form = ColumnForm()
    return render(request, "columns/create_column.html", {"form": form})


@login_required(login_url='/login')
def delete_column(request, column_id, board_id):
    column = Column.objects.get(id=column_id)
    board = Board.objects.get(id=board_id)
    if column in board.column.all():
        column.delete()
        return redirect('/boards/{}'.format(board_id))
    else:
        return render(request, "account_pages/warning.html")


@login_required(login_url='/login')
def edit_column(request, column_id, board_id):
    if request.method == "POST":
        column_prev = Column.objects.get(id=column_id)
        board = Board.objects.get(id=board_id)
        if column_prev in board.column.all():
            form = ColumnForm(request.POST, instance=column_prev)
            if form.is_valid():
                column = form.save(commit=False)
                column.save()
                # board.column.add(column)
                return redirect('/boards/{}'.format(board_id))
        else:
            return render(request, "account_pages/warning.html")
    else:
        form = ColumnForm()
    return render(request, "columns/create_column.html", {"form": form})

mysite/apps/register/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .forms import RegisterForm


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(request, username=form.cleaned_data['username'],

                                password=form.cleaned_data['password1'],
                                )
            login(request, user)
            form.save()
            return render(request, "account_pages/home.html", {})
    else:
        form = RegisterForm()
    return render(request, "register/register.html", {"form": form})

mysite/apps/tasks/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.utils import timezone
from tasks.forms import CommentForm, TaskForm
from columns.models import Column
from tasks.models import Comment, Task


@login_required(login_url='/login')
def create_task(request, column_id, board_id):
    if request.method == "POST":
        column = Column.objects.get(id=column_id)
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.column = column
            task.author = request.user
            task.pub_date = timezone.now()
            task.save()
            column.task.add(task)
        return redirect('/boards/{}'.format(board_id))
    else:
        form = TaskForm()
    return render(request, "tasks/create_task.html", {'form': form})


@login_required(login_url='/login')
def delete_task(request, task_id, column_id, board_id):
    task = Task.objects.get(id=task_id)
    column = Column.objects.get(id=column_id)
    if task in column.task.all():
        task.delete()
        return redirect('/boards/{}'.format(board_id))
    else:
        return render(request, "account_pages/warning.html")


@login_required(login_url='/login')
def edit_task(request, task_id, column_id, board_id):
    if request.method == "POST":
        task_prev = Task.objects.get(id=task_id)
        column = Column.objects.get(id=column_id)
        if task_prev in column.task.all():
            form = TaskForm(request.POST, instance=task_prev)
            if request.user == task_prev.author:
                if form.is_valid():
                    task = form.save(commit=False)
                    # task.column = column
                    task.pub_date = timezone.now()
                    # task.author = request.user
                    # task.lead_time = ...
                    task.save()
                    # column.task.add(task)
                return redirect('/boards/{}'.format(board_id))
            else:
                return render(request, "account_pages/warning.html")
        else:
            return render(request, "account_pages/warning.html")
    else:
        form = TaskForm()
        return render(request, "tasks/create_task.html", {'form': form})


@login_required(login_url='/login')
def complete_task(request, task_id, column_id, board_id):
    task = Task.objects.get(id=task_id)
    column = Column.objects.get(id=column_id)
    if task in column.task.all():
        task.is_completed = True
        task.save()
        return redirect('/boards/{}'.format(board_id))
    else:
        return render(request, "account_pages/warning.html")


# @login_required(login_url='/login')
# def leave_comment(request, task_id, board_id):
#     task = Task.objects.get(id=board_id)
#     task.comment_set.create(author=request.user, comment_text="jgfj")

mysite/templates/account_pages/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>{% block title %}Site{% endblock %}</title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		{% load static %}
		<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	</head>
	<body>
		<header>
			<nav class="navbar navbar-expand-sm main-padding" id="menuheader">
				<a class="navbar-brand" href="#">
					<img src="{% static 'img/logo.png' %}" alt="Logo" class="logo">
				</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<img src="{% static 'img/hamburger.jpg' %}" class="navbar-toggler-icon">
				</button>
				<!-- Links -->
				<div class="collapse navbar-collapse" id="navbarNav">
					<ul class="navbar-nav mr-auto">
						<li class="nav-item">
							<a class="nav-link" href="/">Home</a>
						</li>
						{% if user.is_authenticated %}
							<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" id="navbarDropBoards" data-toggle="dropdown">Boards</a>
							<div class="dropdown-menu">
								{% for board in user.boards.all %}
									<a class="dropdown-item" href="{% url 'boards:detail' board.id %}">{{board.board_title}}</a>
								{% endfor %}
								<a class="dropdown-item highlighted" href="/boards/create_board ">Create new board</a>
							</div>
						</li>
						{% endif %}
<!--						{% if task_list %}-->
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="navbarDropTasks" data-toggle="dropdown">Tasks</a>
								<div class="dropdown-menu">
								{% for column in board.column.all %}
									{% for task in column.task.all %}
									<a class="dropdown-item" href="">{{task}}</a>
									{% endfor %}
								{% endfor %}
								</div>
							</li>
<!--						{% endif %}-->
					</ul>
					<ul class="navbar-nav">
						{% if user.is_authenticated %}
								<li class="nav-item">
									<a class="nav-link" href="/logout">Log out</a>
								</li>
								<li class="nav-item">
									<a class="nav-link" href="/">{{user.username}}</a>
								</li>
						{% else %}
								<li class="nav-item">
									<a class="nav-link" href="/login">Log in</a>
								</li>
								<li class="nav-item">
									<a class="nav-link" href="/register">Sign up</a>
								</li>
						{% endif %}
					</ul>
				</div>
			</nav>
		</header>
		{% if not board %}
			<div class="container">
				<div id="content" name="content" class="main">
					{% if user.is_authenticated %}
						<h1 class="mt-2">{{user.username}}</h1>
						<hr class="mt-0">
					{% endif %}
					{% block content %}
						<!-- For some staff -->
					{% endblock %}
				</div>
			</div>
		{% else %}
			{% block board %}
			{% endblock %}
		{% endif %}
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	</body>
</html>

mysite/templates/account_pages/home.html
{% extends 'account_pages/base.html' %}
{% block title %} TeamPlanner {% endblock %}
{% block content %}

    {% if user.is_authenticated %}
        <p>
            <a class="btn btn-primary" href="/boards/create_board">Create new board</a>
        </p>
        <h3>Your boards</h3>
        {% if user.boards %}
            {% for board in user.boards.all %}
                <a class="dropdown-item item-list" href="{% url 'boards:detail' board.id%}">{{board.board_title}}</a>
            {% endfor %}
        {% else %}
            <div class="alert alert-info">
                Not Found. Create your first board!
            </div>
        {% endif %}
        <br>

        {% else %}
            <h3 class="text-center">Welcome to the TeamPlanner!</h3>
            <br>
            <p class="text-center">
                <img src="http://127.0.0.1:8000/static/img/logo.png">
            </p>
            <br>
            <div class="row">
                <div class="col-sm-6 text-center">
                    <a href="/login" role="button" class="btn btn-primary" style="width:100%">Log in</a>
                </div>
                <div class="col-sm-6 text-center">
                    <a href="/register" role="button" class="btn btn-primary" style="width:100%">Sign up</a>
                </div>
            </div>
    {% endif %}

{% endblock %}

mysite/templates/account_pages/no_such_user.html
{% extends 'account_pages/base.html' %}
{% block title %} Last {% endblock %}

{% block content %}
<p>There is no user with such name, or you made a misspelling! Please try again.</p>
{% endblock %}

mysite/templates/account_pages/warning.html
{% extends 'account_pages/base.html' %}
{% block title %} Last {% endblock %}

{% block content %}
<p>Sorry, but you do not have access to this board. Please <a href="/login">log in</a></p>
{% endblock %}